name: Test and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.11.9-management-alpine
        env:
          RABBITMQ_DEFAULT_USER: volta
          RABBITMQ_DEFAULT_PASS: volta
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Run coverage
        run: go test -v ./. -coverprofile=coverage -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage
